config/routes.rb
Rails.application.routes.draw do
  get 'port/home'
  get 'port/projects'
  get 'port/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root "port#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/port_controller.rb
class PortController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/port_helper.rb
module PortHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portafolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
  </head>

  <body class="surp">
    <nav class="navbar navbar-expand-sm my-fondo fixed-top">
      <div class="container-fluid">
          <%= link_to "Portafolio", port_home_path, class: "navbar-brand mx-5 logotext text-white" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav ms-auto mx-5">
                  <li class="nav-item">
                      <%= link_to "Inicio", port_home_path, class: "nav-link active text-white" %>
                  </li>
                  <li class="nav-item">
                      <%= link_to "Projectos", port_projects_path, class: "nav-link active text-white" %>
                  </li>
                  <li class="nav-item">
                      <%= link_to "Contactos", port_contact_path, class: "nav-link active text-white" %>
                  </li>
              </ul>
          </div>
      </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
    <footer class="mt-4">
      <div class="row">
          <div class="col-6 text-center">
            <h2><%= link_to "Contactos", port_contact_path, class: "nav-link active text-white" %></h2>
          </div>

          <div class="col-6 text-center">
              <%= image_tag 'github.svg', class: 'links_img' %>
              <%= image_tag 'linkedin.svg', class: 'links_img' %>
          </div>
      </div>
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/port/contact.html.erb
<br>

app/views/port/home.html.erb
<br>
<section class="fondo d-none d-md-block">
    <div class="container">
        <div class="row text-white">
            <h2 id="quien" class="text-center mt-5 text-white">¿QUIENES SOMOS?</h2>
            <hr>
            <div class="col-12 col-md-4 col-lg-4 mt-5">
                <div class="avioncito">
                    <img src="assets/img/avion.svg" alt="">
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore unde recusandae quis eaque
                    voluptatum
                    aut earum odio ipsam consequuntur rerum iste ad tempore, at, quibusdam obcaecati necessitatibus
                    reprehenderit eius similique!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet totam, error voluptate ea
                    aspernatur
                    animi voluptatem eaque praesentium, unde saepe soluta nemo fugit perferendis assumenda ex ut
                    accusamus debitis! Asperiores?
                </p>
            </div>

            <div class="col-12 col-md-4 col-lg-4 mt-5">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore unde recusandae quis eaque
                    voluptatum
                    aut earum odio ipsam consequuntur rerum iste ad tempore, at, quibusdam obcaecati necessitatibus
                    reprehenderit eius similique!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet totam, error voluptate ea
                    aspernatur
                    animi voluptatem eaque praesentium, unde saepe soluta nemo fugit perferendis assumenda ex ut
                    accusamus debitis! Asperiores?
                </p>
                <div class="avioncito">
                    <img src="assets/img/avion.svg" alt="">
                </div>
            </div>

            <div class="col-12 col-md-4 col-lg-4 mt-5">
                <div class="avioncito">
                    <img src="assets/img/avion.svg" alt="">
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore unde recusandae quis eaque
                    voluptatum
                    aut earum odio ipsam consequuntur rerum iste ad tempore, at, quibusdam obcaecati necessitatibus
                    reprehenderit eius similique!
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet totam, error voluptate ea
                    aspernatur
                    animi voluptatem eaque praesentium, unde saepe soluta nemo fugit perferendis assumenda ex ut
                    accusamus debitis! Asperiores?
                </p>
            </div>
        </div>
    </div>
</section>

app/views/port/projects.html.erb
<br>
<section class="tarjetas">
    <div class="container">
        <div class="row text-white">
            <div class="row w-100 align-items-center">
                <div class="col text-center">
                    <h2 id="destacados" class="mt-4">DESTACADOS</h2>
                    <hr>
                </div>
            </div>
            <div class="col-12 col-md-3 col-lg-3">
                <div class="card">
                    <%= image_tag 'meet.png', class: 'port_img' %>
                    <div class="card-body">
                        <h5 class="card-title">MeetCoffee</h5>
                        <p class="card-text">Mus enim elementum dignissim class eleifend justo, ut nunc magnis est
                            vulputate nostra, blandit erat luctus faucibus orci.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-3 col-lg-3">
                <div class="card">
                    <%= image_tag 'ricomida.png', class: 'port_img' %>
                    <div class="card-body">
                        <h5 class="card-title">Ricomida</h5>
                        <p class="card-text">Mus enim elementum dignissim class eleifend justo, ut nunc magnis est
                            vulputate nostra, blandit erat luctus faucibus orci.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-3 col-lg-3">
                <div class="card">
                    <%= image_tag 'suricata.png', class: 'port_img' %>
                    <div class="card-body">
                        <h5 class="card-title">Suricata</h5>
                        <p class="card-text">Mus enim elementum dignissim class eleifend justo, ut nunc magnis est
                            vulputate nostra, blandit erat luctus faucibus orci.
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-3 col-lg-3">
                <div class="card">
                    <%= image_tag 'viajes.png', class: 'port_img' %>
                    <div class="card-body">
                        <h5 class="card-title">Viajes Chile</h5>
                        <p class="card-text">Mus enim elementum dignissim class eleifend justo, ut nunc magnis est
                            vulputate nostra, blandit erat luctus faucibus orci.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>